# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55b735c7ee78a313d20f54cf1dc9552c4610bbd509f6a58d843d9bc9b260e80c39d2aeb16d159de2bd4db5a74e5b8a8af04103798be32efb98f8c6f6617f129e

test:
  secret_key_base: 994385f4822a106c6508d019867c2ad90b1e841b4688478e9bc94c9adce77a9b301e50ea1eae236e4fce895137f3c4e5e0f359c3f15b2ee0448a25019e016412

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
